#!/usr/bin/env python3
"""Where POKO's eyes are, frame by frame, written out as src/games/poko/eyes.ts.

The boss wears glasses for the whole mini-game, and the eyes do not sit still:
`look` turns the head 26px either way, `walk` bobs and sways, the side views
bob 4px. Glasses anchored to one measured frame slide off the eyes on the
others. So every frame the game shows is measured, and the glasses read the
anchor for the frame that is actually on screen.

Each eye is a connected dark blob in the upper part of the frame. (An earlier
version split all dark pixels at the median x, which drew one eye 52px wide
out of two 25px eyes and read hair edges as eyes in the side views.)

    python3 scripts/eye_measure.py          # writes src/games/poko/eyes.ts
"""
from __future__ import annotations

import glob
import os

import numpy as np
from PIL import Image
from scipy import ndimage

HERE = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
ROOT = os.path.join(HERE, 'public/assets/images/dokkaebi-v2/poko')
OUT = os.path.join(HERE, 'src/games/poko/eyes.ts')
POSES = [('idle', 'front'), ('look', 'front'), ('walk', 'front'),
         ('walk', 'left'), ('walk', 'right')]


def blobs(path: str) -> list[tuple[float, float, int]]:
    a = np.asarray(Image.open(path).convert('RGBA')).astype(np.float32)
    dark = (a[..., :3].max(axis=2) < 110) & (a[..., 3] > 200)
    dark[int(a.shape[0] * 0.62):, :] = False
    lab, n = ndimage.label(dark)
    out = []
    for i in range(1, n + 1):
        ys, xs = np.nonzero(lab == i)
        if len(xs) >= 30:
            out.append(((xs.min() + xs.max()) / 2, (ys.min() + ys.max()) / 2, xs.max() - xs.min() + 1))
    return sorted(out)


def main() -> int:
    rows = []
    for action, direction in POSES:
        for f in sorted(glob.glob(os.path.join(ROOT, action, direction, '*.webp'))):
            key = os.path.relpath(f, os.path.join(HERE, 'public'))
            found = blobs(f)
            if direction == 'front':
                if len(found) != 2:
                    raise SystemExit(f'{key}: expected two eyes, found {len(found)}')
                (lx, ly, _), (rx, ry, _) = found
                rows.append(f"  '/{key}': [{lx:g}, {rx:g}, {(ly + ry) / 2:g}],")
            else:
                if len(found) != 1:
                    raise SystemExit(f'{key}: expected one eye, found {len(found)}')
                x, y, _ = found[0]
                rows.append(f"  '/{key}': [{x:g}, {x:g}, {y:g}],")
    with open(OUT, 'w', encoding='utf-8') as fh:
        fh.write('// Generated by scripts/eye_measure.py. Do not edit by hand.\n')
        fh.write('//\n// Eye centres in frame pixels (292x420), per frame: [left x, right x, y].\n')
        fh.write('// Side views have one visible eye, so both x are the same.\n')
        fh.write('export const EYE_ANCHORS: Readonly<Record<string, readonly [number, number, number]>> = {\n')
        fh.write('\n'.join(rows) + '\n}\n')
    print(f'{len(rows)} frames -> {os.path.relpath(OUT, HERE)}')
    return 0


if __name__ == '__main__':
    raise SystemExit(main())
