// Generated by scripts/eye_measure.py. Do not edit by hand.
//
// Eye centres in frame pixels (292x420), per frame: [left x, right x, y].
// Side views have one visible eye, so both x are the same.
export const EYE_ANCHORS: Readonly<Record<string, readonly [number, number, number]>> = {
  '/assets/images/dokkaebi-v2/poko/idle/front/poko_idle_front_01.webp': [107, 185, 189],
  '/assets/images/dokkaebi-v2/poko/idle/front/poko_idle_front_02.webp': [107, 185, 189],
  '/assets/images/dokkaebi-v2/poko/idle/front/poko_idle_front_03.webp': [107, 185, 188.25],
  '/assets/images/dokkaebi-v2/poko/idle/front/poko_idle_front_04.webp': [107, 185, 188],
  '/assets/images/dokkaebi-v2/poko/look/front/poko_look_front_01.webp': [107, 185, 189],
  '/assets/images/dokkaebi-v2/poko/look/front/poko_look_front_02.webp': [134.5, 209.5, 189],
  '/assets/images/dokkaebi-v2/poko/look/front/poko_look_front_03.webp': [107, 185, 189],
  '/assets/images/dokkaebi-v2/poko/look/front/poko_look_front_04.webp': [82.5, 157.5, 189],
  '/assets/images/dokkaebi-v2/poko/walk/front/poko_walk_front_01.webp': [107, 185, 190],
  '/assets/images/dokkaebi-v2/poko/walk/front/poko_walk_front_02.webp': [100.5, 178.5, 187],
  '/assets/images/dokkaebi-v2/poko/walk/front/poko_walk_front_03.webp': [107, 185, 190],
  '/assets/images/dokkaebi-v2/poko/walk/front/poko_walk_front_04.webp': [113.5, 191.5, 187],
  '/assets/images/dokkaebi-v2/poko/walk/left/poko_walk_left_01.webp': [241.5, 241.5, 190],
  '/assets/images/dokkaebi-v2/poko/walk/left/poko_walk_left_02.webp': [241.5, 241.5, 188],
  '/assets/images/dokkaebi-v2/poko/walk/left/poko_walk_left_03.webp': [241.5, 241.5, 190],
  '/assets/images/dokkaebi-v2/poko/walk/left/poko_walk_left_04.webp': [241.5, 241.5, 186],
  '/assets/images/dokkaebi-v2/poko/walk/right/poko_walk_right_01.webp': [49.5, 49.5, 190],
  '/assets/images/dokkaebi-v2/poko/walk/right/poko_walk_right_02.webp': [49.5, 49.5, 185.5],
  '/assets/images/dokkaebi-v2/poko/walk/right/poko_walk_right_03.webp': [49.5, 49.5, 190],
  '/assets/images/dokkaebi-v2/poko/walk/right/poko_walk_right_04.webp': [49.5, 49.5, 188],
}
